// constants/caseStudiesData.ts

import { TFunction } from "i18next";

export const getCaseStudies = (t: TFunction) => [
  {
    id: 1,
    title: t('caseStudies.projects.idigitek.title'),
    subtitle: t('caseStudies.projects.idigitek.subtitle'),
    image: "/assets/images/idigitek/Screenshot 2026-06-12 at 02.34.21.png",
    category: t('caseStudies.projects.idigitek.category'),
    duration: t('caseStudies.projects.idigitek.duration'),
    team: t('caseStudies.projects.idigitek.team'),
    technologies: ["React", "Node.js", "Express.js", "MongoDB", "i18next", "Role-Based Access Control (RBAC)", "RESTful API", "Material-UI"],
    problem: t('caseStudies.projects.idigitek.problem'),
    solution: t('caseStudies.projects.idigitek.solution'),
    results: t('caseStudies.projects.idigitek.results', { returnObjects: true }) as string[],
    features: t('caseStudies.projects.idigitek.features', { returnObjects: true }) as string[],
    link: "https://www.idigitek.com/",
    color: "from-purple-500 to-pink-600"
  },
  {
    id: 2,
    title: t('caseStudies.projects.bishola.title'),
    subtitle: t('caseStudies.projects.bishola.subtitle'),
    image: "/assets/images/bishola/Screenshot 2026-06-12 at 02.37.35.png",
    category: t('caseStudies.projects.bishola.category'),
    duration: t('caseStudies.projects.bishola.duration'),
    team: t('caseStudies.projects.bishola.team'),
    technologies: ["NestJS", "Next.js", "PostgreSQL", "React Native", "JWT", "Tailwind CSS"],
    problem: t('caseStudies.projects.bishola.problem'),
    solution: t('caseStudies.projects.bishola.solution'),
    results: t('caseStudies.projects.bishola.results', { returnObjects: true }) as string[],
    features: t('caseStudies.projects.bishola.features', { returnObjects: true }) as string[],
    link: "https://bishola.com/en",
    androidLink: "https://play.google.com/store/search?q=bishola&c=apps",
    iosLink: "https://apps.apple.com/us/app/bishola/id6751427088",
    color: "from-indigo-600 to-purple-600"
  },
  {
    id: 3,
    title: t('caseStudies.projects.hajjUmrah.title'),
    subtitle: t('caseStudies.projects.hajjUmrah.subtitle'),
    image: "/assets/images/hajj-umrah/architecture.png",
    category: t('caseStudies.projects.hajjUmrah.category'),
    duration: t('caseStudies.projects.hajjUmrah.duration'),
    team: t('caseStudies.projects.hajjUmrah.team'),
    technologies: ["Laravel", "Vue.js", "MySQL", "Redis Queues", "Tailwind CSS", "Bootstrap"],
    problem: t('caseStudies.projects.hajjUmrah.problem'),
    solution: t('caseStudies.projects.hajjUmrah.solution'),
    results: t('caseStudies.projects.hajjUmrah.results', { returnObjects: true }) as string[],
    features: t('caseStudies.projects.hajjUmrah.features', { returnObjects: true }) as string[],
    link: "#-nda",
    isNDA: true,
    color: "from-emerald-600 to-teal-500"
  },
  {
    id: 4,
    title: t('caseStudies.projects.layandent.title'),
    subtitle: t('caseStudies.projects.layandent.subtitle'),
    image: "/assets/images/Layan/Layan-1.png",
    category: t('caseStudies.projects.layandent.category'),
    duration: t('caseStudies.projects.layandent.duration'),
    team: t('caseStudies.projects.layandent.team'),
    technologies: ["Next.js", "React", "Tailwind CSS", "Node.js", "MongoDB"],
    problem: t('caseStudies.projects.layandent.problem'),
    solution: t('caseStudies.projects.layandent.solution'),
    results: t('caseStudies.projects.layandent.results', { returnObjects: true }) as string[],
    features: t('caseStudies.projects.layandent.features', { returnObjects: true }) as string[],
    link: "https://layan-medical.vercel.app/",
    color: "from-blue-500 to-cyan-500"
  },
  {
    id: 5,
    title: t('caseStudies.projects.amwall.title'),
    subtitle: t('caseStudies.projects.amwall.subtitle'),
    image: "/assets/images/Amwall/Amwall-1.png",
    category: t('caseStudies.projects.amwall.category'),
    duration: t('caseStudies.projects.amwall.duration'),
    team: t('caseStudies.projects.amwall.team'),
    technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Firebase"],
    problem: t('caseStudies.projects.amwall.problem'),
    solution: t('caseStudies.projects.amwall.solution'),
    results: t('caseStudies.projects.amwall.results', { returnObjects: true }) as string[],
    features: t('caseStudies.projects.amwall.features', { returnObjects: true }) as string[],
    link: "https://www.amwall.net/",
    color: "from-blue-500 to-cyan-500"
  },
  {
    id: 6,
    title: t('caseStudies.projects.storeIt.title'),
    subtitle: t('caseStudies.projects.storeIt.subtitle'),
    image: "/assets/images/storeIt.png",
    category: t('caseStudies.projects.storeIt.category'),
    duration: t('caseStudies.projects.storeIt.duration'),
    team: t('caseStudies.projects.storeIt.team'),
    technologies: ["Next.js", "React", "TypeScript", "Appwrite", "Tailwind CSS"],
    problem: t('caseStudies.projects.storeIt.problem'),
    solution: t('caseStudies.projects.storeIt.solution'),
    results: t('caseStudies.projects.storeIt.results', { returnObjects: true }) as string[],
    features: t('caseStudies.projects.storeIt.features', { returnObjects: true }) as string[],
    link: "https://store-it-coral-eta.vercel.app/sign-in",
    color: "from-blue-500 to-cyan-500"
  },
  {
    id: 7,
    title: t('caseStudies.projects.liveDoc.title'),
    subtitle: t('caseStudies.projects.liveDoc.subtitle'),
    image: "/assets/images/LiveDoc/live-doc-1.png",
    category: t('caseStudies.projects.liveDoc.category'),
    duration: t('caseStudies.projects.liveDoc.duration'),
    team: t('caseStudies.projects.liveDoc.team'),
    technologies: ["React", "Next.js", "WebSockets", "MongoDB", "Tailwind CSS"],
    problem: t('caseStudies.projects.liveDoc.problem'),
    solution: t('caseStudies.projects.liveDoc.solution'),
    results: t('caseStudies.projects.liveDoc.results', { returnObjects: true }) as string[],
    features: t('caseStudies.projects.liveDoc.features', { returnObjects: true }) as string[],
    link: "https://live-doc-plum.vercel.app/",
    color: "from-blue-500 to-cyan-500"
  }
];